using UnityEngine;
using System.Collections;
using UnityEngine.UI;

public class DuckUI : MonoBehaviour {

	public float maxHealthBarWidth = 165;
	public int maxHealth = 100;
	public RectTransform healthBarBackground;
	public GameObject healthBarText;
	public string healthPrefix = "Health: ";

	int health;

	void Start () {
		addHealth (0);
	}

	void Update () {
		//testings
		if (Input.GetKey (KeyCode.U)) {
			addHealth (5);
		}
		if(Input.GetKey(KeyCode.I)) {
			addHealth (-5);
		}
	}

	//addHealth(0) to update UI with no change
	void addHealth (int amount) {
		health = Mathf.Clamp (health + amount, 0, maxHealth);
		Vector3 newScale = healthBarBackground.sizeDelta;
		newScale.x = Mathf.Clamp(maxHealthBarWidth/maxHealth*health, 0, maxHealthBarWidth);
		healthBarBackground.sizeDelta = newScale;
		healthBarText.GetComponent<Text>().text = healthPrefix + health.ToString ();
		healthBarBackground.GetComponent<Image> ().color = new Color (1 - ((float)(health)/maxHealth), ((float)(health)/maxHealth), 0, 1);
		Debug.Log (health / maxHealth);
	}

}
